### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- Release to the world!
- [x] either mark `amd64` the only supported arch OR change sources for JDK to allow different archs
## Solution

- Merge latest, working (?) version!

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by Salamandar** [comment]
!bookwormtestme

**Comment by Salamandar** [comment]
!bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by orhtej2** [comment]
!testme

**Pull request merged**
