### PR TITLE
proxy pass final slash forgotten

### PR DESCRIPTION
**Pull request by OniriCorpe**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme

**Comment by orhtej2** [comment]
Does it cause any problem? There's a significant semantics difference and in my testing it works as its but reference conf passes to socket so I'm not sure

**Comment by OniriCorpe** [comment]
after testing it, this crashes nginx:
`nginx: [emerg] "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/conf.d/piped.oniricorpe.eu.d/piped.conf:31`

**Comment by orhtej2** [comment]
That can be circumvented as long as proxy is not suppressed to know the path but I feel it should not pass to root

**Pull request closed without merging**
